<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-Shipping.MessageEndpoint-d75caa0c-5b0d-409c-992b-982a28edcd62</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Catalog.Contracts\Catalog.Contracts.csproj" />
    <ProjectReference Include="..\eShop.ServiceDefaults\eShop.ServiceDefaults.csproj" />
    <ProjectReference Include="..\Ordering.Contracts\Ordering.Contracts.csproj" />
  </ItemGroup>
</Project>
